apiVersion: apps/v1
kind: Deployment
metadata:
 name: mavenwebappdeployment
spec:
 replicas: 1
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: mavenwebapp
 template:
  metadata:
   name: mavenwebapppod
   labels:
     app: mavenwebapp	 
  spec: 
    containers:
    - name: mavenwebapp
      image: bharath0812/java:8.0
      ports:
      - containerPort: 8080
