# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B install --file pom.xml
    - name: Build and scan image
      uses: dentsusoken/build-and-scan-image@main
      with:
    # Image name and optionally tag in "name:tag" format
        tag: "bharath0812/java:1.0"
        path: "."
        dockerfile: Dockerfile
        trivy-enable: "true"
        trivy-version: "0.23.0"
        trivy-severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
        trivy-vuln-type: os,library
        trivy-ignore-unfixed: "false"
    
    
    
    
